use optraj_bdd;
SELECT ID_SITE, NUM_SITE, W.craft, W.qualif, NUM_WEEK, NUM_YEAR, count(*) from
(select ID_SITE, NUM_SITE, NUM_WEEK, NUM_YEAR, ID_WORKER
from
SITE inner join
(SELECT ID_SITE, NUM_WEEK, NUM_YEAR, ID_WORKER
FROM (ASSIGNMENT INNER JOIN PHASE ON ASSIGNMENT.ID_PHASE = PHASE.ID)) as B
on SITE.ID = B.ID_SITE) as A
INNER join 
(select WORKER.ID, WORKER.NAME, CRAFT.NAME as craft, QUALIFICATION.NAME as qualif from WORKER join CRAFT join QUALIFICATION
where WORKER.ID_CRAFT = CRAFT.ID and WORKER.ID_QUALIFICATION=QUALIFICATION.ID) as W
ON A.ID_WORKER = W.ID
group by ID_SITE, NUM_SITE,W.craft, W.qualif, NUM_WEEK, NUM_YEAR;